import Navbar from "@/components/Navbar";
import ThemeProvider from "./context";
import "./globals.css";
import { Alexandria } from "next/font/google";
import Footer from "@/components/Footer";
const inter = Alexandria({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body className={inter.className}>
        <ThemeProvider>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
